swagger: "2.0"
info:
  title: API
  description: HTTP API
  version: 1.0.0
host: localhost
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /foo:
    get:
      tags:
      - foo
      summary: Get foo
      operationId: foo#Get
      parameters:
      - name: GetRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FooGetRequestBody'
          required:
          - fromProfileUUID
          - fromProfileID
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FooGetResponseBody'
      schemes:
      - http
definitions:
  FooGetRequestBody:
    title: FooGetRequestBody
    type: object
    properties:
      fromProfileID:
        type: integer
        description: profile id of the endorsement sender
        example: 658594
        minimum: 1
      fromProfileUUID:
        type: string
        description: profile uuid of the endorsement sender
        example: 91533209-d516-41a8-aa93-97e36b4ab195
        format: uuid
      validateMe:
        type: string
        example: one
        enum:
        - one
        - two
    example:
      fromProfileID: 658594
      fromProfileUUID: 91533209-d516-41a8-aa93-97e36b4ab195
      validateMe: one
    required:
    - fromProfileUUID
    - fromProfileID
  FooGetResponseBody:
    title: 'Mediatype identifier: resulttype; view=default'
    type: object
    properties:
      fromProfileID:
        type: integer
        description: profile id of the endorsement sender
        example: 658594
        minimum: 1
      fromProfileUUID:
        type: string
        description: profile uuid of the endorsement sender
        example: 91533209-d516-41a8-aa93-97e36b4ab195
        format: uuid
    description: GetResponseBody result type (default view)
    example:
      fromProfileID: 658594
      fromProfileUUID: 91533209-d516-41a8-aa93-97e36b4ab195
    required:
    - fromProfileUUID
    - fromProfileID
